---
title: "UMAP has better cluster placement than t-SNE"
author: "Justin Lin"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = TRUE)

library(ggplot2)
library(gridExtra)
library(umap)
library(MASS)

source("../../../Algorithms/Out of sample algs.R")
source("../../../Algorithms/Out of sample metrics.R")
source("../../../Algorithms/Plotting tools.R")

set.seed(123)
```

```{r, include=FALSE}
library(reticulate)
use_python("/Users/justinlin/anaconda3/bin/python")
py_config()
py_available()

source_python("../../../Algorithms/TSNE.py", convert = FALSE)
```

```{r}
Z = cbind(rbind(mvrnorm(20, c(-10,3,0,0,0,0), diag(2, nrow = 6)),
                mvrnorm(20, c(-5,-3,0,0,0,0), diag(2, nrow = 6)),
                mvrnorm(20, c(5,0,0,1,0,0), diag(2, nrow = 6)),
                mvrnorm(20, c(10,0,0,4,0,0), diag(2, nrow = 6)),
                mvrnorm(20, c(0,0,0,0,0,7), diag(2, nrow = 6)),
                mvrnorm(20, c(-1,2,0,1,-5,0), diag(2, nrow = 6))),
          matrix(0, nrow = 120, ncol = 4)) + matrix(rnorm(120*10, sd = 1), nrow = 120)
vars = diag(var(Z))


vars = diag(var(Z))

pca = prcomp(Z, center = TRUE, rank. = 3)

Y = pca$x
Y_emb = t(t(Y %*% t(pca$rotation)) + pca$center)

n = dim(Z)[1]
p = dim(Z)[2]
r = dim(Y)[2]
q = 2

var_explained = pca$sdev^2 / sum(pca$sdev^2)
plot(var_explained)
lines(var_explained)
```

```{r}
perplexity = 15
n_neighbors = 80
k = 20

trans_tsne = tsne(Z, perplexity, n_components=as.integer(q))
X_tsne = py_to_r(trans_tsne)

trans_umap = umap(Z, method = 'umap-learn', n_neighbors = n_neighbors, n_components = q)
X_umap = trans_umap$layout

plot(X_tsne)
plot(X_umap)
```


```{r, include=FALSE}
b = 60
num_pts = 40
indices = sample(1:n, num_pts)
noise_proportion = 0.5

y = Y[indices,]
z = t(t(y %*% t(pca$rotation)) + pca$center)

risks_tsne = risks_umap = matrix(nrow = num_pts, ncol = 4)

for (i in 1:num_pts) {
  new_pts = matrix(rep(z[i,], each = b), nrow = b) + matrix(rnorm(b * p, 0, rep(sqrt(vars*noise_proportion), b)), nrow = b)

  stress_tsne = stress_umap = 0
  dist_cor_tsne = dist_cor_umap = 0
  
  og_stress_tsne = og_stress_umap = 0
  og_dist_cor_tsne = og_dist_cor_umap = 0
  
  xs_tsne = py_to_r(predict_tsne(trans_tsne, new_pts))
  xs_umap = predict(trans_umap, new_pts)
  
  for (j in 1:b) {
    new_pt = new_pts[j,]
    
    x_tsne = xs_tsne[j,]
    x_umap = xs_umap[j,]

    stress_tsne = stress_tsne + stress(Y, y[i,], X_tsne, x_tsne)
    dist_cor_tsne = dist_cor_tsne + dist_cor(Y, y[i,], X_tsne, x_tsne)

    stress_umap = stress_umap + stress(Y, y[i,], X_umap, x_umap)
    dist_cor_umap = dist_cor_umap + dist_cor(Y, y[i,], X_umap, x_umap)
    
    og_stress_tsne = og_stress_tsne + stress(Z, new_pt, X_tsne, x_tsne)
    og_dist_cor_tsne = og_dist_cor_tsne + dist_cor(Z, new_pt, X_tsne, x_tsne)

    og_stress_umap = og_stress_umap + stress(Z, new_pt, X_umap, x_umap)
    og_dist_cor_umap = og_dist_cor_umap + dist_cor(Z, new_pt, X_umap, x_umap)
  }
  
  risks_tsne[i,] = c(stress_tsne/b, dist_cor_tsne/b, og_stress_tsne/b, og_dist_cor_tsne/b)
  risks_umap[i,] = c(stress_umap/b, dist_cor_umap/b, og_stress_umap/b, og_dist_cor_umap/b)
}
```

```{r}
df = data.frame(stress = c(risks_tsne[,1], risks_umap[,1]),
                dist_cor = c(risks_tsne[,2], risks_umap[,2]),
                og_stress = c(risks_tsne[,3], risks_umap[,3]),
                og_dist_cor = c(risks_tsne[,4], risks_umap[,4]),
                type = c(rep("t-SNE", num_pts), rep("UMAP", num_pts)))
```

```{r, fig.width=12, fig.height=8}
p1 = ggplot(df, aes(x = stress, y = type, color = type, group = type)) + geom_boxplot() + xlim(0,1)
p2 = ggplot(df, aes(x = dist_cor, y = type, color = type, group = type)) + geom_boxplot() + xlim(0,1)
p3 = ggplot(df, aes(x = og_stress, y = type, color = type, group = type)) + geom_boxplot() + xlim(0,1)
p4 = ggplot(df, aes(x = og_dist_cor, y = type, color = type, group = type)) + geom_boxplot() + xlim(0,1)

grid.arrange(p1, p2, p3, p4, ncol = 2)
```