---
title: "Changing signal dimension r"
author: "Justin Lin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = TRUE)

library(tidyverse)
library(readxl)
library(umap)
library(gridExtra)
library(ggplot2)

source("../../Algorithms/Out of sample algs.R")
source("../../Algorithms/Out of sample metrics.R")
source("../../Algorithms/Plotting tools.R")
```


```{r, include=FALSE}
library(reticulate)
use_python("/Users/justinlin/anaconda3/bin/python")
py_config()
py_available()

source_python("../../Algorithms/TSNE.py", convert = FALSE)
```

```{r}
Z = matrix(rnorm(100*20, sd = 5) + runif(100*20, min = -1, max = 3) + runif(100, min = -5, max = -1),
           nrow = 100,
           ncol = 20)
vars = diag(var(Z))

r_high = 17
r_med = 7
r_low = 3

pca_high = prcomp(Z, center = TRUE, scale. = TRUE, rank = r_high)
pca_med = prcomp(Z, center = TRUE, scale. = TRUE, rank = r_med)
pca_low = prcomp(Z, center = TRUE, scale. = TRUE, rank = r_low)

Y_high = pca_high$x
Y_med = pca_med$x
Y_low = pca_low$x

Y_emb_high = t(t(Y_high %*% t(pca_high$rotation)) * pca_high$scale + pca_high$center)
Y_emb_med = t(t(Y_med %*% t(pca_med$rotation)) * pca_med$scale + pca_med$center)
Y_emb_low = t(t(Y_low %*% t(pca_low$rotation)) * pca_low$scale + pca_low$center)

n = dim(Z)[1]
p = dim(Z)[2]
q = 2

var_explained = pca_high$sdev^2 / sum(pca_high$sdev^2)
plot(var_explained)
lines(var_explained)
```


```{r}
perplexity = n_neighbors = k = 20

X_mds = cmdscale(dist(Z, method = "minkowski", p = 2))

trans_tsne = tsne(Z, perplexity)
X_tsne = py_to_r(trans_tsne)

trans_umap = umap(Z, method = 'umap-learn', n_neighbors = n_neighbors, n_components = q)
X_umap = trans_umap$layout

plot(X_mds)
plot(X_tsne)
plot(X_umap)
```

```{r, include=FALSE}
b = 80
num_pts = 40
indices = sample(1:n, num_pts)

y_high = Y_high[indices,]
y_med = Y_med[indices,]
y_low = Y_low[indices,]

z_high = t(t(y_high %*% t(pca_high$rotation)) * pca_high$scale + pca_high$center)
z_med = t(t(y_med %*% t(pca_med$rotation)) * pca_med$scale + pca_med$center)
z_low = t(t(y_low %*% t(pca_low$rotation)) * pca_low$scale + pca_low$center)
```

```{r, include=FALSE}
risks_kpca_high = risks_tsne_high = risks_umap_high = matrix(nrow = num_pts, ncol = 5)

for (i in 1:num_pts) {
  new_pts = matrix(rep(z_high[i,], each = b), nrow = b) + matrix(rnorm(b * p, 0, rep(sqrt(vars/10), b)),
                                                                 nrow = b)
  
  trusts_kpca = trusts_tsne = trusts_umap = 0
  cont_kpca = cont_tsne = cont_umap = 0
  prec_kpca = prec_tsne = prec_umap = 0
  stresses_kpca = stresses_tsne = stresses_umap = 0
  dist_cor_kpca = dist_cor_tsne = dist_cor_umap = 0
  
  xs_tsne = py_to_r(predict_tsne(trans_tsne, new_pts))
  xs_umap = predict(trans_umap, new_pts)
  
  for (j in 1:b) {
    new_pt = new_pts[j,]
    
    A2 = as.matrix(dist(rbind(Z,new_pt), method = "minkowski", p = 2)^2)
    x_kpca = Trosset_approx(X_mds, A2)
    
    x_tsne = xs_tsne[j,]
    x_umap = xs_umap[j,]
    
    trusts_kpca = trusts_kpca + trustworthiness(Y_high, y_high[i,], X_mds, x_kpca, k = k)
    cont_kpca = cont_kpca + continuity(Y_high, y_high[i,], X_mds, x_kpca, k = k)
    prec_kpca = prec_kpca + precision(Y_high, y_high[i,], X_mds, x_kpca, k = k)
    stresses_kpca = stresses_kpca + stress(Y_high, y_high[i,], X_mds, x_kpca)
    dist_cor_kpca = dist_cor_kpca + dist_cor(Y_high, y_high[i,], X_mds, x_kpca)
    
    trusts_tsne = trusts_tsne + trustworthiness(Y_high, y_high[i,], X_tsne, x_tsne, k = k)
    cont_tsne = cont_tsne + continuity(Y_high, y_high[i,], X_tsne, x_tsne, k = k)
    prec_tsne = prec_tsne + precision(Y_high, y_high[i,], X_tsne, x_tsne, k = k)
    stresses_tsne = stresses_tsne + stress(Y_high, y_high[i,], X_tsne, x_tsne)
    dist_cor_tsne = dist_cor_tsne + dist_cor(Y_high, y_high[i,], X_tsne, x_tsne)
    
    trusts_umap = trusts_umap + trustworthiness(Y_high, y_high[i,], X_umap, x_umap, k = k)
    cont_umap = cont_umap + continuity(Y_high, y_high[i,], X_umap, x_umap, k = k)
    prec_umap = prec_umap + precision(Y_high, y_high[i,], X_umap, x_umap, k = k)
    stresses_umap = stresses_umap + stress(Y_high, y_high[i,], X_umap, x_umap)
    dist_cor_umap = dist_cor_umap + dist_cor(Y_high, y_high[i,], X_umap, x_umap)
  }
  
  risks_kpca_high[i,] = c(trusts_kpca/b, cont_kpca/b, prec_kpca/b, stresses_kpca/b, dist_cor_kpca/b)
  risks_tsne_high[i,] = c(trusts_tsne/b, cont_tsne/b, prec_tsne/b, stresses_tsne/b, dist_cor_tsne/b)
  risks_umap_high[i,] = c(trusts_umap/b, cont_umap/b, prec_umap/b, stresses_umap/b, dist_cor_umap/b)
}
```

```{r, include=FALSE}
risks_kpca_med = risks_tsne_med = risks_umap_med = matrix(nrow = num_pts, ncol = 5)

for (i in 1:num_pts) {
  new_pts = matrix(rep(z_med[i,], each = b), nrow = b) + matrix(rnorm(b * p, 0, rep(sqrt(vars/10), b)), nrow = b)
  
  trusts_kpca = trusts_tsne = trusts_umap = 0
  cont_kpca = cont_tsne = cont_umap = 0
  prec_kpca = prec_tsne = prec_umap = 0
  stresses_kpca = stresses_tsne = stresses_umap = 0
  dist_cor_kpca = dist_cor_tsne = dist_cor_umap = 0
  
  xs_tsne = py_to_r(predict_tsne(trans_tsne, new_pts))
  xs_umap = predict(trans_umap, new_pts)
  
  for (j in 1:b) {
    new_pt = new_pts[j,]
    
    A2 = as.matrix(dist(rbind(Z,new_pt), method = "minkowski", p = 2)^2)
    x_kpca = Trosset_approx(X_mds, A2)
    
    x_tsne = xs_tsne[j,]
    x_umap = xs_umap[j,]
    
    trusts_kpca = trusts_kpca + trustworthiness(Y_med, y_med[i,], X_mds, x_kpca, k = k)
    cont_kpca = cont_kpca + continuity(Y_med, y_med[i,], X_mds, x_kpca, k = k)
    prec_kpca = prec_kpca + precision(Y_med, y_med[i,], X_mds, x_kpca, k = k)
    stresses_kpca = stresses_kpca + stress(Y_med, y_med[i,], X_mds, x_kpca)
    dist_cor_kpca = dist_cor_kpca + dist_cor(Y_med, y_med[i,], X_mds, x_kpca)
    
    trusts_tsne = trusts_tsne + trustworthiness(Y_med, y_med[i,], X_tsne, x_tsne, k = k)
    cont_tsne = cont_tsne + continuity(Y_med, y_med[i,], X_tsne, x_tsne, k = k)
    prec_tsne = prec_tsne + precision(Y_med, y_med[i,], X_tsne, x_tsne, k = k)
    stresses_tsne = stresses_tsne + stress(Y_med, y_med[i,], X_tsne, x_tsne)
    dist_cor_tsne = dist_cor_tsne + dist_cor(Y_med, y_med[i,], X_tsne, x_tsne)
    
    trusts_umap = trusts_umap + trustworthiness(Y_med, y_med[i,], X_umap, x_umap, k = k)
    cont_umap = cont_umap + continuity(Y_med, y_med[i,], X_umap, x_umap, k = k)
    prec_umap = prec_umap + precision(Y_med, y_med[i,], X_umap, x_umap, k = k)
    stresses_umap = stresses_umap + stress(Y_med, y_med[i,], X_umap, x_umap)
    dist_cor_umap = dist_cor_umap + dist_cor(Y_med, y_med[i,], X_umap, x_umap)
  }
  
  risks_kpca_med[i,] = c(trusts_kpca/b, cont_kpca/b, prec_kpca/b, stresses_kpca/b, dist_cor_kpca/b)
  risks_tsne_med[i,] = c(trusts_tsne/b, cont_tsne/b, prec_tsne/b, stresses_tsne/b, dist_cor_tsne/b)
  risks_umap_med[i,] = c(trusts_umap/b, cont_umap/b, prec_umap/b, stresses_umap/b, dist_cor_umap/b)
}
```

```{r, include=FALSE}
risks_kpca_low = risks_tsne_low = risks_umap_low = matrix(nrow = num_pts, ncol = 5)

for (i in 1:num_pts) {
  new_pts = matrix(rep(z_low[i,], each = b), nrow = b) + matrix(rnorm(b * p, 0, rep(sqrt(vars/10), b)), nrow = b)
  
  trusts_kpca = trusts_tsne = trusts_umap = 0
  cont_kpca = cont_tsne = cont_umap = 0
  prec_kpca = prec_tsne = prec_umap = 0
  stresses_kpca = stresses_tsne = stresses_umap = 0
  dist_cor_kpca = dist_cor_tsne = dist_cor_umap = 0
  
  xs_tsne = py_to_r(predict_tsne(trans_tsne, new_pts))
  xs_umap = predict(trans_umap, new_pts)
  
  for (j in 1:b) {
    new_pt = new_pts[j,]
    
    A2 = as.matrix(dist(rbind(Z,new_pt), method = "minkowski", p = 2)^2)
    x_kpca = Trosset_approx(X_mds, A2)
    
    x_tsne = xs_tsne[j,]
    x_umap = xs_umap[j,]
    
    trusts_kpca = trusts_kpca + trustworthiness(Y_low, y_low[i,], X_mds, x_kpca, k = k)
    cont_kpca = cont_kpca + continuity(Y_low, y_low[i,], X_mds, x_kpca, k = k)
    prec_kpca = prec_kpca + precision(Y_low, y_low[i,], X_mds, x_kpca, k = k)
    stresses_kpca = stresses_kpca + stress(Y_low, y_low[i,], X_mds, x_kpca)
    dist_cor_kpca = dist_cor_kpca + dist_cor(Y_low, y_low[i,], X_mds, x_kpca)
    
    trusts_tsne = trusts_tsne + trustworthiness(Y_low, y_low[i,], X_tsne, x_tsne, k = k)
    cont_tsne = cont_tsne + continuity(Y_low, y_low[i,], X_tsne, x_tsne, k = k)
    prec_tsne = prec_tsne + precision(Y_low, y_low[i,], X_tsne, x_tsne, k = k)
    stresses_tsne = stresses_tsne + stress(Y_low, y_low[i,], X_tsne, x_tsne)
    dist_cor_tsne = dist_cor_tsne + dist_cor(Y_low, y_low[i,], X_tsne, x_tsne)
    
    trusts_umap = trusts_umap + trustworthiness(Y_low, y_low[i,], X_umap, x_umap, k = k)
    cont_umap = cont_umap + continuity(Y_low, y_low[i,], X_umap, x_umap, k = k)
    prec_umap = prec_umap + precision(Y_low, y_low[i,], X_umap, x_umap, k = k)
    stresses_umap = stresses_umap + stress(Y_low, y_low[i,], X_umap, x_umap)
    dist_cor_umap = dist_cor_umap + dist_cor(Y_low, y_low[i,], X_umap, x_umap)
  }
  
  risks_kpca_low[i,] = c(trusts_kpca/b, cont_kpca/b, prec_kpca/b, stresses_kpca/b, dist_cor_kpca/b)
  risks_tsne_low[i,] = c(trusts_tsne/b, cont_tsne/b, prec_tsne/b, stresses_tsne/b, dist_cor_tsne/b)
  risks_umap_low[i,] = c(trusts_umap/b, cont_umap/b, prec_umap/b, stresses_umap/b, dist_cor_umap/b)
}
```

```{r, fig.width=12, fig.height=12}
dat_kpca = data.frame(trust = c(risks_kpca_high[,1], risks_kpca_med[,1], risks_kpca_low[,1]),
                      cont = c(risks_kpca_high[,2], risks_kpca_med[,2], risks_kpca_low[,2]),
                      prec = c(risks_kpca_high[,3], risks_kpca_med[,3], risks_kpca_low[,3]),
                      dist_cor = c(risks_kpca_high[,5], risks_kpca_med[,5], risks_kpca_low[,5]),
                      r = c(rep(r_high, num_pts), rep(r_med, num_pts), rep(r_low, num_pts)))
                      
p1 = ggplot(dat_kpca, aes(x = trust)) +
  geom_density(data = subset(dat_kpca, r == r_high), fill = "#43a2ca", alpha = 0.7) +
  geom_density(data = subset(dat_kpca, r == r_med), fill = "#a8ddb5", alpha = 0.7) + 
  geom_density(data = subset(dat_kpca, r == r_low), fill = "#e0f3db", alpha = 0.7)

p2 = ggplot(dat_kpca, aes(x = cont)) +
  geom_density(data = subset(dat_kpca, r == r_high), fill = "#43a2ca", alpha = 0.7) +
  geom_density(data = subset(dat_kpca, r == r_med), fill = "#a8ddb5", alpha = 0.7) + 
  geom_density(data = subset(dat_kpca, r == r_low), fill = "#e0f3db", alpha = 0.7)

p3 = ggplot(dat_kpca, aes(x = prec)) +
  geom_density(data = subset(dat_kpca, r == r_high), fill = "#43a2ca", alpha = 0.7) +
  geom_density(data = subset(dat_kpca, r == r_med), fill = "#a8ddb5", alpha = 0.7) + 
  geom_density(data = subset(dat_kpca, r == r_low), fill = "#e0f3db", alpha = 0.7)

p4 = ggplot(dat_kpca, aes(x = dist_cor)) +
  geom_density(data = subset(dat_kpca, r == r_high), fill = "#43a2ca", alpha = 0.7) +
  geom_density(data = subset(dat_kpca, r == r_med), fill = "#a8ddb5", alpha = 0.7) + 
  geom_density(data = subset(dat_kpca, r == r_low), fill = "#e0f3db", alpha = 0.7)

grid.arrange(p1, p2, p3, p4, ncol = 2)
```

```{r, fig.width=12, fig.height=12}
dat_tsne = data.frame(trust = c(risks_tsne_high[,1], risks_tsne_med[,1], risks_tsne_low[,1]),
                      cont = c(risks_tsne_high[,2], risks_tsne_med[,2], risks_tsne_low[,2]),
                      prec = c(risks_tsne_high[,3], risks_tsne_med[,3], risks_tsne_low[,3]),
                      dist_cor = c(risks_tsne_high[,5], risks_tsne_med[,5], risks_tsne_low[,5]),
                      r = c(rep(r_high, num_pts), rep(r_med, num_pts), rep(r_low, num_pts)))
                      
p1 = ggplot(dat_tsne, aes(x = trust)) +
  geom_density(data = subset(dat_tsne, r == r_high), fill = "#43a2ca", alpha = 0.7) +
  geom_density(data = subset(dat_tsne, r == r_med), fill = "#a8ddb5", alpha = 0.7) + 
  geom_density(data = subset(dat_tsne, r == r_low), fill = "#e0f3db", alpha = 0.7)

p2 = ggplot(dat_tsne, aes(x = cont)) +
  geom_density(data = subset(dat_tsne, r == r_high), fill = "#43a2ca", alpha = 0.7) +
  geom_density(data = subset(dat_tsne, r == r_med), fill = "#a8ddb5", alpha = 0.7) + 
  geom_density(data = subset(dat_tsne, r == r_low), fill = "#e0f3db", alpha = 0.7)

p3 = ggplot(dat_tsne, aes(x = prec)) +
  geom_density(data = subset(dat_tsne, r == r_high), fill = "#43a2ca", alpha = 0.7) +
  geom_density(data = subset(dat_tsne, r == r_med), fill = "#a8ddb5", alpha = 0.7) + 
  geom_density(data = subset(dat_tsne, r == r_low), fill = "#e0f3db", alpha = 0.7)

p4 = ggplot(dat_tsne, aes(x = dist_cor)) +
  geom_density(data = subset(dat_tsne, r == r_high), fill = "#43a2ca", alpha = 0.7) +
  geom_density(data = subset(dat_tsne, r == r_med), fill = "#a8ddb5", alpha = 0.7) + 
  geom_density(data = subset(dat_tsne, r == r_low), fill = "#e0f3db", alpha = 0.7)

grid.arrange(p1, p2, p3, p4, ncol = 2)
```

```{r, fig.width=12, fig.height=12}
dat_umap = data.frame(trust = c(risks_umap_high[,1], risks_umap_med[,1], risks_umap_low[,1]),
                      cont = c(risks_umap_high[,2], risks_umap_med[,2], risks_umap_low[,2]),
                      prec = c(risks_umap_high[,3], risks_umap_med[,3], risks_umap_low[,3]),
                      dist_cor = c(risks_umap_high[,5], risks_umap_med[,5], risks_umap_low[,5]),
                      r = c(rep(r_high, num_pts), rep(r_med, num_pts), rep(r_low, num_pts)))
                      
p1 = ggplot(dat_umap, aes(x = trust)) +
  geom_density(data = subset(dat_umap, r == r_high), fill = "#43a2ca", alpha = 0.7) +
  geom_density(data = subset(dat_umap, r == r_med), fill = "#a8ddb5", alpha = 0.7) + 
  geom_density(data = subset(dat_umap, r == r_low), fill = "#e0f3db", alpha = 0.7)

p2 = ggplot(dat_umap, aes(x = cont)) +
  geom_density(data = subset(dat_umap, r == r_high), fill = "#43a2ca", alpha = 0.7) +
  geom_density(data = subset(dat_umap, r == r_med), fill = "#a8ddb5", alpha = 0.7) + 
  geom_density(data = subset(dat_umap, r == r_low), fill = "#e0f3db", alpha = 0.7)

p3 = ggplot(dat_umap, aes(x = prec)) +
  geom_density(data = subset(dat_umap, r == r_high), fill = "#43a2ca", alpha = 0.7) +
  geom_density(data = subset(dat_umap, r == r_med), fill = "#a8ddb5", alpha = 0.7) + 
  geom_density(data = subset(dat_umap, r == r_low), fill = "#e0f3db", alpha = 0.7)

p4 = ggplot(dat_umap, aes(x = dist_cor)) +
  geom_density(data = subset(dat_umap, r == r_high), fill = "#43a2ca", alpha = 0.7) +
  geom_density(data = subset(dat_umap, r == r_med), fill = "#a8ddb5", alpha = 0.7) + 
  geom_density(data = subset(dat_umap, r == r_low), fill = "#e0f3db", alpha = 0.7)

grid.arrange(p1, p2, p3, p4, ncol = 2)
```