---
title: "Trust vs Shep (microbiome)"
author: "Justin Lin for ISCC"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = TRUE)

library(ggplot2)
library(MASS)
library(dplyr)
library(Rtsne)
library(scatterplot3d)
library(viridis)
library(gridExtra)
library(readr)
library(phyloseq)

source("../../../Algorithms/DR metrics.R")
load("phyloseq_objects.RData")
```

```{r}
data = as.data.frame(t(as.matrix(otu_table(abt))))
data = data %>%
  select_if(function(x) mean(x == 0) < 0.5)

log_data = data %>% 
  mutate_all(function(x) log(x + 1))

Z = as.matrix(log_data)
```

```{r}
pca = prcomp(Z, center = TRUE, .scale = TRUE)

var_explained = pca$sdev^2 / sum(pca$sdev^2)
plot(var_explained)
lines(var_explained)
```


```{r}
n = dim(Z)[1]
p = dim(Z)[2]
r = 2

Y = prcomp(Z, center = TRUE, scale. = TRUE, rank. = r)$x
```

```{r}
perplexity = seq(from = 5, to = 50, by = 5)
b = 20
k = 10

trusts = sheps = vector(length = length(perplexity)*b)
trusts_noise = sheps_noise = vector(length = length(perplexity)*b)

for (i in 1:length(perplexity)) {
  for (j in 1:b) {
    X_tsne = Rtsne(Z, perplexity = perplexity[i])$Y
    
    trusts[(i-1)*b + j] = trustworthiness_full(Y, X_tsne, k)
    sheps[(i-1)*b + j] = dist_cor_full(Y, X_tsne)
    
    trusts_noise[(i-1)*b + j] = trustworthiness_full(Z, X_tsne, k)
    sheps_noise[(i-1)*b + j] = dist_cor_full(Z, X_tsne)
  }
}
```

```{r, echo=FALSE, fig.width=12, fig.height=4}
df = data.frame(perplexity = rep(perplexity, each = b),
                trust = trusts,
                shep = sheps,
                trust_noise = trusts_noise,
                shep_noise = sheps_noise)

p1 = ggplot(df, aes(x = trust, y = shep, col = perplexity)) + 
  geom_point() + 
  scale_color_viridis() + 
  labs(x = "Trustworthiness", y = "Shepard Goodness", title = "Replicating Signal")
  

p2 = ggplot(df, aes(x = trust_noise, y = shep_noise, col = perplexity)) + 
  geom_point() + 
  scale_color_viridis() + 
  labs(x = "Trustworthiness", y = "Shepard Goodness", title = "Replicating Signal + Noise")

grid.arrange(p1, p2, nrow = 1)
```