---
title: "scRNA-seq Plots"
author: "Justin Lin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(gridExtra)
library(viridis)

load("trust vs shep (umap scRNA-seq).Rda")
```

```{r, echo=FALSE, fig.width=18, fig.height=6}
grid.arrange(p2, p1, nrow = 1)
```

```{r, echo=FALSE, fig.width=18, fig.height=6}
q1 = ggplot(df, aes(x = neighbors, y = trust)) + 
  geom_point(size = 2) +
  geom_smooth(method="loess", se=FALSE, color="red") +
  labs(x = "n_neighbors", y = "Trustworthiness", title = "Replicating Signal")

q2 = ggplot(df, aes(x = neighbors, y = trust_noise)) + 
  geom_point(size = 2) +
  geom_smooth(method="loess", se=FALSE, color="red") + 
  labs(x = "n_neighbors", y = "Trustworthiness", title = "Replicating Signal + Noise")

q3 = ggplot(df, aes(x = neighbors, y = shep, col = neighbors)) + 
  geom_point(size = 2) +
  scale_color_viridis() + 
  labs(x = "n_neighbors", y = "Shepard Goodness", title = "Replicating Signal")

q4 = ggplot(df, aes(x = neighbors, y = shep_noise, col = neighbors)) + 
  geom_point(size = 2) +
  scale_color_viridis() + 
  labs(x = "n_neighbors", y = "Shepard Goodness", title = "Replicating Signal + Noise")

grid.arrange(q2, q1, nrow = 1)
grid.arrange(q4, q3, nrow = 1)
```

```{r, fig.width=18, fig.height=6}
grid.arrange(p1, q1, nrow = 1)
```

