---
title: "Breast Cancer Example (Bengio vs. t-SNE)"
author: "Justin Lin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, echo = FALSE)
```

```{r, include=FALSE}
source("../Out of sample algs.R")
source("../Out of sample metrics.R")
library(ggplot2)
library(tidyverse)
library(scatterplot3d)
library(ade4)
library(readxl)
library(viridis)
library(gridExtra)
library(akima)
```

```{r, include=FALSE}
data = read_excel("breast cancer data.xlsx", col_names = FALSE)

data = data %>%
  select(-c(1,2))
```

```{r}
Z = prcomp(data, center = TRUE, scale. = TRUE, tol = 0.1)$x
colnames(Z) = NULL
X_pca = prcomp(Z, rank. = 2)
X = X_pca$x

n = length(Z[,1])
p = length(Z[1,])
q = 2
col_vars = diag(var(Z))

plot(X)
```


```{r, eval=FALSE}
b = 40
vars = col_vars/5

new_pts = matrix(rnorm(b * p, 0, rep(sqrt(vars), b)), ncol = p) + matrix(rep(colMeans(Z), each = b), nrow = b)
```

```{r, eval=FALSE}
t_sne_pts = matrix(nrow = b, ncol = q)
Bengio_pts = matrix(nrow = b, ncol = q)

for (i in 1:b) {
  new_pt = new_pts[i,]
  A2 = as.matrix(dist(rbind(Z,new_pt))^2)
    
  Bengio_pts[i,] = Trosset_approx(X, A2)
  
  start = predict(X_pca, newdata = matrix(c(new_pt), nrow = 1))
  t_sne_pts[i,] = t_sne(Z, new_pt, X, start, sigma = 1.5)
}
```

```{r, eval=FALSE}
data.frame(x = c(X[,1], Bengio_pts[,1], t_sne_pts[,1]),
           y = c(X[,2], Bengio_pts[,2], t_sne_pts[,2]),
           type = c(rep("Original Data", n), rep("Bengio", b), rep("t-SNE", b))) %>%
  ggplot(aes(x = x, y = y, color = type)) + geom_point(size = 1, alpha = 0.5)
```


```{r calculate risks, include=FALSE}
b = 40
num_pts = 30
vars = col_vars/5
k = 20

pt_indices = sample(1:n, num_pts)

risks_Bengio = matrix(nrow = num_pts, ncol = 5)
risks_tsne = matrix(nrow = num_pts, ncol = 5)

for (i in 1:num_pts) {
  new_pts = matrix(rnorm(b * p, 0, rep(sqrt(vars), b)), ncol = p) + matrix(rep(Z[pt_indices[i],], each = b), nrow = b)
  
  trusts_Bengio = vector(length = b)
  conts_Bengio = vector(length = b)
  prec_Bengio = vector(length = b)
  stresses_Bengio = vector(length = b)
  dist_cors_Bengio = vector(length = b)
  
  trusts_tsne = vector(length = b)
  conts_tsne = vector(length = b)
  prec_tsne = vector(length = b)
  stresses_tsne = vector(length = b)
  dist_cors_tsne = vector(length = b)
  
  for (j in 1:b) {
    new_pt = new_pts[j,]
    A2 = as.matrix(dist(rbind(Z,new_pt))^2)
    
    y_Bengio = Trosset_approx(X, A2)
    
    start = predict(X_pca, newdata = matrix(c(new_pt), nrow = 1))
    y_tsne = t_sne(Z, new_pt, X, start, sigma = 1.5)
    
    trusts_Bengio[j] = trustworthiness(Z, Z[pt_indices[i],], X, y_Bengio, k)
    conts_Bengio[j] = continuity(Z, Z[pt_indices[i],], X, y_Bengio, k)
    prec_Bengio[j] = precision(Z, Z[pt_indices[i],], X, y_Bengio, k)
    stresses_Bengio[j] = stress(Z, Z[pt_indices[i],], X, y_Bengio)
    dist_cors_Bengio[j] = dist_cor(Z, Z[pt_indices[i],], X, y_Bengio)
    
    trusts_tsne[j] = trustworthiness(Z, Z[pt_indices[i],], X, y_tsne, k)
    conts_tsne[j] = continuity(Z, Z[pt_indices[i],], X, y_tsne, k)
    prec_tsne[j] = precision(Z, Z[pt_indices[i],], X, y_tsne, k)
    stresses_tsne[j] = stress(Z, Z[pt_indices[i],], X, y_tsne)
    dist_cors_tsne[j] = dist_cor(Z, Z[pt_indices[i],], X, y_tsne)
  }
  
  risks_Bengio[i,] = c(mean(trusts_Bengio), mean(conts_Bengio), mean(prec_Bengio), mean(stresses_Bengio), 
                       mean(dist_cors_Bengio))
  
  risks_tsne[i,] = c(mean(trusts_tsne), mean(conts_tsne), mean(prec_tsne), mean(stresses_tsne), 
                   mean(dist_cors_tsne))
}
```

```{r create plots , include=FALSE}
p_trust_Bengio = data.frame(x = X[pt_indices,1], y = X[pt_indices,2], risks = risks_Bengio[,1]) %>%
  ggplot(aes(x = x, y = y)) + 
  geom_point(aes(color = risks), size = 2) + 
  scale_color_viridis(limits = c(.7,1)) +
  ggtitle("Trustworthiness")

p_cont_Bengio = data.frame(x = X[pt_indices,1], y = X[pt_indices,2], risks = risks_Bengio[,2]) %>%
  ggplot(aes(x = x, y = y)) + 
  geom_point(aes(color = risks), size = 2) + 
  scale_color_viridis(limits = c(.7,1)) +
  ggtitle("Continuity")

p_prec_Bengio = data.frame(x = X[pt_indices,1], y = X[pt_indices,2], risks = risks_Bengio[,3]) %>%
  ggplot(aes(x = x, y = y)) + 
  geom_point(aes(color = risks), size = 2) + 
  scale_color_viridis(limits = c(0,.5)) +
  ggtitle("Projected Precision Score")

p_stress_Bengio = data.frame(x = X[pt_indices,1], y = X[pt_indices,2], risks = risks_Bengio[,4]) %>%
  ggplot(aes(x = x, y = y)) + 
  geom_point(aes(color = risks), size = 2) + 
  scale_color_viridis(limits = c(0,.2),
                       begin = 1,
                       end = 0) +
  ggtitle("Normalized Stress")

p_cor_Bengio = data.frame(x = X[pt_indices,1], y = X[pt_indices,2], risks = risks_Bengio[,5]) %>%
  ggplot(aes(x = x, y = y)) + 
  geom_point(aes(color = risks), size = 2) + 
  scale_color_viridis(limits = c(.6,1)) +
  ggtitle("Correlation of Distances")

p_trust_tsne = data.frame(x = X[pt_indices,1], y = X[pt_indices,2], risks = risks_tsne[,1]) %>%
  ggplot(aes(x = x, y = y)) + 
  geom_point(aes(color = risks), size = 2) + 
  scale_color_viridis(limits = c(.7,1)) +
  ggtitle("Trustworthiness")

p_cont_tsne = data.frame(x = X[pt_indices,1], y = X[pt_indices,2], risks = risks_tsne[,2]) %>%
  ggplot(aes(x = x, y = y)) + 
  geom_point(aes(color = risks), size = 2) + 
  scale_color_viridis(limits = c(.7,1)) +
  ggtitle("Continuity")

p_prec_tsne = data.frame(x = X[pt_indices,1], y = X[pt_indices,2], risks = risks_tsne[,3]) %>%
  ggplot(aes(x = x, y = y)) + 
  geom_point(aes(color = risks), size = 2) + 
  scale_color_viridis(limits = c(0,.5)) +
  ggtitle("Projected Precision Score")

p_stress_tsne = data.frame(x = X[pt_indices,1], y = X[pt_indices,2], risks = risks_tsne[,4]) %>%
  ggplot(aes(x = x, y = y)) + 
  geom_point(aes(color = risks), size = 2) + 
  scale_color_viridis(limits = c(0,.2),
                       begin = 1,
                       end = 0) +
  ggtitle("Normalized Stress")

p_cor_tsne = data.frame(x = X[pt_indices,1], y = X[pt_indices,2], risks = risks_tsne[,5]) %>%
  ggplot(aes(x = x, y = y)) + 
  geom_point(aes(color = risks), size = 2) + 
  scale_color_viridis(limits = c(.6,1)) +
  ggtitle("Correlation of Distances")
```

```{r show Bengio plots, fig.height=18, fig.width=8}
grid.arrange(p_trust_Bengio, p_trust_tsne, p_cont_Bengio, p_cont_tsne, p_prec_Bengio, p_prec_tsne, p_stress_Bengio, p_stress_tsne, p_cor_Bengio, p_cor_tsne, ncol = 2)
```

```{r}
og_errors_Bengio = matrix(nrow = num_pts, ncol = 5)
og_errors_tsne = matrix(nrow = num_pts, ncol = 5)

for (i in 1:num_pts) {
  new_pt = Z[pt_indices[i],]
  A2 = as.matrix(dist(rbind(Z,new_pt))^2)
    
  y_Bengio = Trosset_approx(X, A2)
  
  start = predict(X_pca, newdata = matrix(c(new_pt), nrow = 1))
  y_tsne = t_sne(Z, new_pt, X, start, sigma = 1.5)
  
  og_errors_Bengio[i,1] = trustworthiness(Z, new_pt, X, y_Bengio, k)
  og_errors_Bengio[i,2] = continuity(Z, new_pt, X, y_Bengio, k)
  og_errors_Bengio[i,3] = precision(Z, new_pt, X, y_Bengio, k)
  og_errors_Bengio[i,4] = stress(Z, new_pt, X, y_Bengio)
  og_errors_Bengio[i,5] = dist_cor(Z, new_pt, X, y_Bengio)
  
  og_errors_tsne[i,1] = trustworthiness(Z, new_pt, X, y_tsne, k)
  og_errors_tsne[i,2] = continuity(Z, new_pt, X, y_tsne, k)
  og_errors_tsne[i,3] = precision(Z, new_pt, X, y_tsne, k)
  og_errors_tsne[i,4] = stress(Z, new_pt, X, y_tsne)
  og_errors_tsne[i,5] = dist_cor(Z, new_pt, X, y_tsne)
}
```

```{r}
filled.contour(interp(x = X[pt_indices,1], y = X[pt_indices,2], z = (og_errors_Bengio[,1]-og_errors_tsne[,1])/og_errors_Bengio[,1]),
      color.palette = function(n) hcl.colors(n),
      nlevels = 40,
      zlim = c(0,.03))

filled.contour(interp(x = X[pt_indices,1], y = X[pt_indices,2], z = (risks_Bengio[,1]-risks_tsne[,1])/risks_Bengio[,1]),
      color.palette = function(n) hcl.colors(n),
      nlevels = 40,
      zlim = c(0,.03))
```