---
title: "Calibrating Perplexity"
author: "Justin Lin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = TRUE)

library(ggplot2)
library(gridExtra)
library(MASS)
library(dplyr)
library(Rtsne)

source("../../../Algorithms/DR metrics.R")
```

```{r}
n = 200
r = 6

Y = mvrnorm(n, c(0,0,0,0,0,0), diag(25, nrow = r))
          
```

```{r, include=FALSE}
p = 10
q = 2

k = 10
noise_sd = 8
b = 40
perplexity = c(20, 30, 40, 50, 60)

tsne_error = tsne_noise_error = matrix(nrow = b*length(perplexity), ncol = 3)

for (i in 1:length(perplexity)) {
  error = noise_error = matrix(nrow = b, ncol = 3)
  
  for (j in 1:b) {
    Z = cbind(Y, matrix(0, nrow = n, ncol = p - r)) + matrix(rnorm(n*p, sd = noise_sd), nrow = n, ncol = p)
    
    X_tsne = Rtsne(Z, pca_scale = TRUE, perplexity = perplexity[i])$Y
    
    error[j,1] = trustworthiness_full(Y, X_tsne, k)
    error[j,2] = local_stress_full(Y, X_tsne, k)
    error[j,3] = dist_cor_full(Y, X_tsne)
    
    noise_error[j,1] = trustworthiness_full(Z, X_tsne, k)
    noise_error[j,2] = local_stress_full(Z, X_tsne, k)
    noise_error[j,3] = dist_cor_full(Z, X_tsne)
  }
  
  tsne_error[((i-1)*b + 1):(i*b),] = error
  tsne_noise_error[((i-1)*b + 1):(i*b),] = noise_error
}
```

```{r, include=FALSE}
df_error = data.frame(trust = tsne_error[,1],
                      stress = tsne_error[,2],
                      dist_cor = tsne_error[,3],
                      perplexity = rep(perplexity, each=b))

df_noise_error = data.frame(trust = tsne_noise_error[,1],
                            stress = tsne_noise_error[,2],
                            dist_cor = tsne_noise_error[,3],
                            perplexity = rep(perplexity, each=b))
```

```{r, echo=FALSE, fig.height=12, fig.width=16}
p1 = ggplot(df_error, aes(x = trust, 
                          y = factor(perplexity), 
                          group = factor(perplexity), 
                          col = factor(perplexity))) + 
  geom_boxplot(show.legend = FALSE) + 
  stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black", fill="black") +
  labs(y = "perplexity")

p2 = ggplot(df_error, aes(x = stress, 
                          y = factor(perplexity), 
                          group = factor(perplexity), 
                          col = factor(perplexity))) + 
  geom_boxplot(show.legend = FALSE) + 
  stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black", fill="black") +
  labs(y = "perplexity")

p3 = ggplot(df_error, aes(x = dist_cor, 
                          y = factor(perplexity), 
                          group = factor(perplexity), 
                          col = factor(perplexity))) + 
  geom_boxplot(show.legend = FALSE) + 
  stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black", fill="black") +
  labs(y = "perplexity")

q1 = ggplot(df_noise_error, aes(x = trust, 
                                y = factor(perplexity), 
                                group = factor(perplexity), 
                                col = factor(perplexity))) + 
  geom_boxplot() + 
  stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black", fill="black") +
  labs(y = "")

q2 = ggplot(df_noise_error, aes(x = stress, 
                                y = factor(perplexity), 
                                group = factor(perplexity), 
                                col = factor(perplexity))) + 
  geom_boxplot() + 
  stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black", fill="black") +
  labs(y = "")

q3 = ggplot(df_noise_error, aes(x = dist_cor, 
                                y = factor(perplexity), 
                                group = factor(perplexity), 
                                col = factor(perplexity))) + 
  geom_boxplot() + 
  stat_summary(fun.y=mean, geom="point", shape=18, size=3, color="black", fill="black") +
  labs(y = "")

grid.arrange(p1, q1, p2, q2, p3, q3, ncol = 2)
```
