---
title: "Trust vs Shep (MNIST)"
author: "Justin Lin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = TRUE)

library(ggplot2)
library(MASS)
library(dplyr)
library(Rtsne)
library(scatterplot3d)
library(viridis)
library(gridExtra)

source("../../../Algorithms/DR metrics.R")
```

```{r}
data = read.delim("Data/Exp1_NK_uns_CD4_inf.txt")

data = data %>%
  select(-c(1,2)) %>%
  sample_n(500) %>%
  mutate_all(function(x) log(1+x))
```

```{r}
pca = prcomp(data, center = TRUE, scale. = TRUE, rank. = 10)
Z = pca$x

var_explained = pca$sdev^2 / sum(pca$sdev^2)
plot(var_explained)
lines(var_explained)
```


```{r}
n = dim(Z)[1]
p = dim(Z)[2]
r = 2

Y = Z[,c(1,2)]
```

```{r}
perplexity = seq(from = 10, to = 160, by = 10)
b = 20
k = 10

trusts = sheps = vector(length = length(perplexity)*b)
trusts_noise = sheps_noise = vector(length = length(perplexity)*b)

for (i in 1:length(perplexity)) {
  for (j in 1:b) {
    X_tsne = Rtsne(Z, perplexity = perplexity[i])$Y
    
    trusts[(i-1)*b + j] = trustworthiness_full(Y, X_tsne, k)
    sheps[(i-1)*b + j] = dist_cor_full(Y, X_tsne)
    
    trusts_noise[(i-1)*b + j] = trustworthiness_full(Z, X_tsne, k)
    sheps_noise[(i-1)*b + j] = dist_cor_full(Z, X_tsne)
  }
}
```

```{r, echo=FALSE, fig.width=18, fig.height=6}
df = data.frame(perplexity = rep(perplexity, each = b),
                trust = trusts,
                shep = sheps,
                trust_noise = trusts_noise,
                shep_noise = sheps_noise)

p1 = ggplot(df, aes(x = trust, y = shep, col = perplexity)) + 
  geom_point(size = 2) + 
  scale_color_viridis() + 
  labs(x = "Trustworthiness", y = "Shepard Goodness", title = "Replicating Signal")
  

p2 = ggplot(df, aes(x = trust_noise, y = shep_noise, col = perplexity)) + 
  geom_point(size = 2) + 
  scale_color_viridis() + 
  labs(x = "Trustworthiness", y = "Shepard Goodness", title = "Replicating Signal + Noise")

grid.arrange(p1, p2, nrow = 1)
```

```{r}
# save(Y, df, p1, p2, file = "trust vs shep (CyTOF).Rda")
```

